name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install -y libopenmpi-dev libhdf5-mpi-dev
        python -m pip install --upgrade pip
        python -m pip install pylint pytest pytest-cov
        python -m pip install jupyter
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        CC="mpicc" HDF5_MPI="ON" pip install --upgrade --force-reinstall --no-binary=h5py h5py
        pip install .
        pip install .[ci]
      env:
        CC: mpicc
        HDF5_MPI: ON
